name: "ArgoCD Sync"
description: "Sync your ArgoCD application from GitHub"
author: "flxxyz"
inputs:
  address:
    description: "ArgoCD server address"
    required: true
  token:
    description: "ArgoCD token"
    required: true
  insecure:
    description: "insecure"
    required: false
    default: 'false'
  plaintext:
    description: "plaintext, use http instead of https"
    required: false
    default: 'false'
  appName:
    description: "Application name to sync"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'anchor'
  color: 'green'
