name: Integration Test
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Import Vault Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            argocd/data/token admin | ARGOCD_TOKEN ;

      - name: Self test
        id: selftest
        uses: flxxyz/argocd-sync@main
        with:
          address: ${{ secrets.ARGOCD_ADDR }}
          token: ${{ steps.secrets.outputs.ARGOCD_TOKEN }}
          insecure: false
          appName: horusec-platform

  argocd-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Import Vault Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          namespace: Analytics
          secrets: |
            analytics-secret/data/spark-deployment/argocd/token admin | ARGOCD_TOKEN ;

      - name: "Sync ArgoCD Application"
        id: selftest
        uses: flxxyz/argocd-sync@main
        with:
          address: ${{ secrets.ARGOCD_ADDR }}
          token: ${{ steps.secrets.outputs.ARGOCD_TOKEN }}
          insecure: false
          appName: cost-analyzer
